INSERT INTO grupo (codigo, nome, codigo_registro) VALUES ( 1, 'Administrador', NULL);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES ( 2, 'Acupuntura', 5, 1);
INSERT INTO grupo (codigo, nome, codigo_registro) VALUES ( 3, 'Advocacia', 18);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES ( 4, 'Clínica Geral', 11, 1);
INSERT INTO grupo (codigo, nome, codigo_registro) VALUES ( 5, 'Contabilidade', 6);
INSERT INTO grupo (codigo, nome, codigo_registro) VALUES ( 6, 'Enfermagem', 2);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES ( 7, 'Fisioterpia', 10, 1);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES ( 8, 'Fonoaudiologia', 13, 1);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES ( 9, 'Neuropediatria', 11, 1);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES (10, 'Nutrição', 15, 1);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES (11, 'Odontologia', 16, 1);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES (12, 'Ortopedia', 11, 1);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES (13, 'Pediatria', 11, 1);
INSERT INTO grupo (codigo, nome, codigo_registro, anamnese) VALUES (14, 'Psicologia', 17, 1);
INSERT INTO grupo (codigo, nome, codigo_registro) VALUES (15, 'Recepcionista', NULL);
